ArangoDB-Community/pyArango

pyArango/query.py, pyArango/tests/tests.py
=> Fixes missing import of CreationError

pyArango/doc/source/index.rst
Hi, I've fixed some issues on the front page of the documentation.
=> fixed typos in documentation

.travis.yml
So you can see how PRs will increase or decrease test coverage
https://codecov.io/gh/tariqdaouda/pyArango/pull/36
=> report coverage

pyArango/collection.py
found while clicking through the 10 minutes python...
=> We need the CONST to be defined if we use it later on.

README.rst
Avoid some newcomers (like me) errors
=> Readme imports from uppercase to lowercase

examples/debiangraph.py
this is @zarath s fix of the debian graph example.
=> Fix debian branch

README.rst
there is no pyArango.validator module: it was probably a typo
=> fix import in example code

README.rst, examples/createSocialGraph.py, examples/debiangraph.py, examples/fetchDebianDependencyGraph.py
add more examples and some documentation about them.
=> Add example social graph

examples/createSocialGraph.py
example createSocialGraph.py not work probably
=> fix example for examples/createSocialGraph.py

README.rst
Checked the python syntax and code conventions for the code examples.
=> Overall pep8 for the code examples

pyArango/database.py
=> New method for database: deleteAllCollection

pyArango/collection.py
Additional bulk import parameters exists per documentation:
https://docs.arangodb.com/3.3/HTTP/BulkImports/
=> Allow additional bulk import optional parameters

pyArango/database.py, pyArango/document.py
=> Fix createDocument initDict misspelling

pyArango/collection.py, pyArango/theExceptions.py
I saw issue #43 earlier today and decided to create something to add the functionality.  I wanted to use the export API as well.
=> Add function to use ArangoDB's export API

pyArango/collection.py
Hi,
I haved functionality for deduplication for indexing a list.
Regards,
Dilip Vamsi.
=> Added Deduplication for indexing a list

.travis.yml, pyArango/connection.py, pyArango/database.py, pyArango/gevent_session.py, pyArango/query.py, pyArango/theExceptions.py
Hi @tariqdaouda @dothebart ,
I have added the functionality. Please check for changes
Regards,
Dilip Vamsi.
=> fixed 'requests (new session for request)', 'grequests (basic auth, jwt auto reset, send with max retries)'.

pyArango/connection.py, pyArango/database.py, pyArango/foxx.py, pyArango/gevent_session.py, pyArango/tests/tests.py
As @tariqdaouda suggested, I have created a pull request to dev and closing the current in master.
=> Added foxx executor and minor fixes on grequest session

examples/createSocialGraph.py
Resolves https://github.com/ArangoDB-Community/pyArango/issues/178
```
self.relation = self.db.createCollection('Edges', 'relation')
TypeError: createCollection() takes from 1 to 2 positional arguments but 3 were given
```
=> Fix social example

CHANGELOG.rst
Fix some typos in CHANGELOG.rst
=> fix some typos in CHANGELOG.rst

README.rst
Fix two small typos in README.rst
=> fix small typos in readme

README.rst, pyArango/database.py, pyArango/document.py, pyArango/query.py, pyArango/tests/tests.py, pyArango/theExceptions.py
Maybe it can be better to add a method for this feature and implement the contains method to check if a collection exist or not.
Can rewrite it that way if required.
=> Add __contains__ method to allow to easily check if an id reference a valid document

README.rst, pyArango/database.py, pyArango/document.py, pyArango/query.py, pyArango/theExceptions.py
Resolve Unresolved reference 'store'
=> Fix __contains__ method. Missing self prefix
