ArangoDB-Community/pyArango

- pyArango/collection.py
Returned string for edge collection types was misspelled as 'egde'
> Fixing typo (egde to edge)

- pyArango/collection.py
- pyArango/connection.py
When misusing db.createCollection() the error message is meaningless to a novice user. improve this.
Hopefully git works for me this time ;-)
> Import error reporting when misusing db.CreateCollection()

- pyArango/database.py
- pyArango/query.py
Proposing to add functionality similar to the one in this PR. We need to be able to serialize slightly more complex objects than the ones the standard JSONEncoder can handle (such as datetime etc). Our solution was to pull out a json_encoder parameter to allow us to inject a custom encoder. Did not seem to be possible to do in any other way.
> Adding possibilty to inject custom JSONEncoder into AQLQuery.

- README.rst
- pyArango/connection.py
- pyArango/database.py
- pyArango/query.py
- setup.py
Hi, 
I've been working a bit to get pyArango emmit statsd statistics:
https://www.datadoghq.com/blog/statsd/
Basically one can use the statsd protocol to fire and forget send statistics via udp to a central service. 
Statsd will collect them, and aggredate them to an average, 95% percentile and some other values in a configured frequency.
Since its not that important all measured metrics actually arrive on the statsd side to get meaning full values, the UDP connection is basically used as a fire and forget thing, which should make the instrumentation lightweight to pyArango in terms of resource usage.
It should only be enabled if pyArango is initialized using this. 
I've used it in conjunction with the statsd implementation of http://colletd.org and it worked fine for me
I'd like to …
> first draft for adding statsd reporting

- pyArango/document.py
`CachedDoc`s used to fail when used as vertices in `link()` method. `_from` and `_to` would fall through without being set due to class mismatches. This semi-implicitly checks for `CachedDoc` by checking for the `document` property, and adds an error condition if no properties are found and the `_from` and `_to` properties are not set.
> Enable usage of CachedDocs in Edge link()

- pyArango/query.py
404 is returned by the server when cursor has expired during batch processing.
> Handle cursor 404 during batch processing

- pyArango/document.py
- pyArango/tests/tests.py
The problem for me was that pyArango implicitly expects nested fields to be validated as well. In the `DocumentStore` you find the following lines in the `set()` and `__setitem__ `
methods:
```python
if isinstance(value, dict) :
if field in self.validators:
vals = self.validators[field]
else :
vals = {}
self.store[field] = DocumentStore(self.collection, validators = vals, initDct = value, patch =         
self.patching, subStore=True, validateInit=self.validateInit)      
```
These lines check if the current value of the field is a dictionary and if that is the case, the validators of this fields are redirected into the sup `DataStore`. This is problematic if your field definition looks like this:
```python
_fields = {
"nested_something": Field()
}
```
If you now set `nested_something` to …
> Issue 87 problem with unvalidated nested data

- pyArango/collection.py
- pyArango/document.py
- pyArango/query.py
- pyArango/tests/tests.py
I changed `x.__class__ is Y` everywhere to `instanceof(x, Y)` where x is an object so that we can use subclasses of Y as well. This is useful in case we're injecting our own documentClass for a collection since the function to link documents are looking for instances of Document to use the `_id` property.
> Is is used insted of instanceof

- pyArango/collection.py
- pyArango/tests/tests.py
I added the return of the details for a bulk import to the end user of this library. We needed this for taking further actions and give the user feedback how their data import went. 
It's a simple one line addition. I also added tests for the case of an exception and for the case of the return of the description data from the import.
Cheers
P.S. I had to fix on etest case in the unit tests and I added a ARANGODB_URL environmen var, in case some (like me) has running arango on a different port.
> Return details for bulk imports

- pyArango/collection.py
This PR should close #113 #119 .
> fix `'_key' in collection` check `__contains__` method

- .travis.yml
- setup.cfg
don't make `python setup.py` install gevent, rather use apt for this since this is less error prone.
> pre-install gevent

- pyArango/admin.py
- pyArango/collection.py
- pyArango/document.py
- pyArango/tests/setup_arangodb.sh
- pyArango/tests/tests.py
- pyArango/theExceptions.py
- add first wrapper for `admin` series calls to detect whether we're talking to a cluster or a single server
- add getResponsibleShard() to documents
- add named indices
- tests may now execute different tests depending on version and cluster of the SUT.
> Feature/add new 3.5 apis

- pyArango/collection.py
- pyArango/doc/source/conf.py
While trying to bulk import a local JSON file, I got an error and found this simple-to-fix bug.  I chose lower case `url` as the standard variable name based on other usage in the module.
This is my first contribution to `pyArango`, let me know if anything else needs to be done to get this merged in.
Thanks!
> Fix url variable case for bulkImport methods.

- pyArango/action.py
- pyArango/connection.py
- pyArango/database.py
- pyArango/foxx.py
- pyArango/tasks.py
- pyArango/tests/tests.py
Example.
```python
>>> from pyArango import connection
>>> conn = connection.Connection(username, password)
>>> test_db = conn['test']
>>> test_db.foxx.services
[{'mount': '/_admin/aardvark',
'name': 'aardvark',
'version': '3.0.0',
'provides': {},
'development': False,
'legacy': False},
{'mount': '/_api/foxx',
'name': 'foxx-manager',
'version': '3.2.0',
'provides': {},
'development': False,
'legacy': False}]
>>> test_db.foxx.mounts
{'/_admin/aardvark', '/_api/foxx'}
>>> test_db.foxx.service('/_admin/aardvark').get('/index.html')
<Response [200]>
>>> test_db.action.get('/_admin/aardvark/index.html')
<Response [200]>
>>> conn.action.get('/_db/test/_admin/aardvark/index.html')
<Response [200]>
>>> test_db.tasks.create('sample-task', 'console.log("sample-task", new Date());', period=10) …
```
> Connection, database actions and foxx can only be called when mount exists. Added tasks in Database

- pyArango/query.py
This pull is to fix the issue #160, instead of returning an empty array when there is no more item, the query should call for the next batch instead. Inside the `nextBatch()` function already handle the iteration stop when running out of result.
> Fix abnormal aqlQuery

- pyArango/collection.py
This pull request only aims to add a 'deduplicate' option to collection.ensurePersistentIndex.
> Add 'deduplicate' option for ensurePersistentIndex

- README.rst
- pyArango/database.py
Also added two new graph (cluster) option parameters:
- replicationFactor
- writeConcern
See: https://www.arangodb.com/docs/stable/http/gharial-management.html#create-a-graph
Simple example:
```
from pyArango.connection import *
from pyArango.collection import Collection, Edges, Field
from pyArango.graph import Graph, EdgeDefinition
databaseName = "satellite_graph_db"
conn = Connection()
try:
conn.createDatabase(name=databaseName)
except Exception:
pass
db = conn[databaseName] # all databases are loaded automatically into the connection and are accessible in this fashion
class Humans(Collection):
_fields = {
"name": Field()
}
class Friend(Edges):
_fields = {
"lifetime": Field()
}
class MySatelliteGraph(Graph) :
_edgeDefinitions = [EdgeDefinition("Friend", fromCollections=["Humans"], …
```
> Added support for satellite graphs

- examples/json_schema_validation_in_db.py
change "validation" attribute name to "schema" after the corresponding API changed during the ArangoDB 3.7 alpha phase.
> change "validation" attribute name to "schema"

- run_tests.sh
This script will provide an easy integration for @arangodb developers to run this drivers unittests.
https://github.com/arangodb/arangodb/pull/12684 is the upstream PR that adds these functionality.
TBC: could/should we  use python virtualenv here? and if yes, how to?
Such an invocation could look like this:
```
./scripts/unittest driver --driversource ../pyArango
================================================================================
Executing test driver
================================================================================
2020-09-22T15:56:13Z [1181202] S INFO [e52b0] {general} ArangoDB 3.8.0-devel enterprise [linux-DEBUG] 64bit maintainer mode, using build heads/devel-0-gb89c9bd98f4-dirty, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1g  21 Apr …
```
> add simple driver test wrapper script

- pyArango/connection.py
- pyArango/tests/tests.py
This PR should give PyArango users a greater level or granularity for dictating the http header timeout. Most users should not need to use this, but it will be extremely useful to have so those than do.
The use case I found personally was in a multinode Kubernetes configuration in the event of node death the connection would hang indefinitely but using this simple http header in the AikidoSesson object I was able to avoid this and the connection would sever itself after the allocated timeout. 
I've included parameter in the standard Connection object so that users can access it easily without the need for excessive alternations to their code or the PyArango library.
Given that the likelihood of this connection issue is very minimal I think that a default timeout of 30 seconds should be …
> Adding timeout to session object for hanging connections

- pyArango/collection.py
This commit reformats the doc-strings in the 'collection.py' file. Also, fixed some typos and misspellings. The doc-strings are now capitalized, and the 'arguments' and 'keywords' are sandwiched between single quotations.
[1] https://peps.python.org/pep-0257/
I read the `contributing guidelines` which said I should open pull requests to the `dev` branch if it is not a critical merge. But it failed to merge automatically. So I opened it for this one which works out fine. Is it OK or should I just retry with using `dev` as my base branch?
Thanks for all the good work 👍
> Collection: reformat doc-strings to follow PEP 257

- CHANGELOG.rst
- pyArango/collection.py
- pyArango/connection.py
- pyArango/database.py
- pyArango/document.py
- pyArango/tests/tests.py
- pyArango/theExceptions.py
- setup.py
* Added getitem for documents at the database level
* Added fill_default() on documents to replace None values by schema defaults
* fill_default() is automatically called on save
> Feature fill defaults

- CHANGELOG.rst
- pyArango/connection.py
This PR adds support for passing in the `cert` parameter to the session object (through the `AikidoSession` class).
I hope adding a new headline (with a new version number) to `CHANGELOG.rst` was the right move here. LMK if I should do this differently.
Limitations:
* I don't have time right how to understand `grequests` well enough to add this feature there as well. But I think throwing an exception in that case is better than not having client-side certificate support at all).
* I've reviewed the `tests` directory but don't really know where I would add a test for a feature like this. Would it be ok to merge this even though the `CONTRIBUTING.md` states that
> If you add a new feature please provide a test for it. Otherwise your pull request might be rejected.
> Add support for client-side certificates

- CHANGELOG.rst
- pyArango/document.py
- setup.py
When a document field is accessed if it is missing from the schema the default value is automatically set. 
Handles the edege case where a field might be deleted from the database
> added default setting on field access
